-- 각 도서별 판매 수
# WITH TBL AS
# (SELECT BOOK_ID, SUM(SALES) TOTAL_AMOUNT
# FROM BOOK_SALES
# WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
# GROUP BY BOOK_ID)

# SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_AMOUNT*PRICE) TOTAL_SALES
# FROM BOOK b
# JOIN AUTHOR a
# ON a.AUTHOR_ID = b.AUTHOR_ID
# JOIN TBL t
# ON b.BOOK_ID = t.BOOK_ID
# GROUP BY AUTHOR_ID, CATEGORY
# ORDER BY AUTHOR_ID, CATEGORY DESC

SELECT a.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) TOTAL_SALES
FROM AUTHOR a
JOIN BOOK b
ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
AND SALES_DATE < '2022-02-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
