# SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) SALES
# FROM PRODUCT a JOIN OFFLINE_SALE b
# ON a.PRODUCT_ID = b.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE

SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) SALES FROM PRODUCT p
JOIN OFFLINE_SALE o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE