/*
2022년 10월 16일에 대여 중인 자동차인 경우 '대여중', 아닐 경우 '대여 가능'
반납 날짜가 2022년 10월 16일인 경우에도 '대여중'
자동차 ID와 AVAILABILITY 리스트를 출력
자동차 ID를 기준으로 내림차순 정렬
*/
WITH CTE AS(
SELECT CAR_ID,
SUM(CASE
WHEN END_DATE < "2022-10-16" OR "2022-10-16" < START_DATE THEN 0
ELSE 1
END) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID)

SELECT CAR_ID,
CASE
WHEN AVAILABILITY = 0 THEN '대여 가능'
ELSE '대여중' END
AS AVAILABILITY
FROM CTE
ORDER BY CAR_ID DESC