-- 완료된 중고 거래의 총금액이 70만 원 이상
-- 회원 ID, 닉네임, 총거래금액 조회
-- 총거래금액을 기준 오름차순 정렬

# SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
# FROM USED_GOODS_BOARD a
# JOIN USED_GOODS_USER b
# ON a.WRITER_ID = b.USER_ID
# WHERE STATUS = 'DONE'
# GROUP BY USER_ID, NICKNAME -- 집계함수를 안 쓰면 GROUP BY 기준에 추가해야함 (USER_ID만 GROUP BY 하면안댐)
# HAVING SUM(PRICE) >= 700000
# ORDER BY TOTAL_SALES

SELECT USER_ID, NICKNAME, SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b
ON a.WRITER_ID = b.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC