# SELECT MCDP_CD 진료과코드, COUNT(APNT_NO) 5월예약건수 FROM APPOINTMENT
# WHERE APNT_YMD BETWEEN '2022-05-01' AND '2022-05-31'
# GROUP BY MCDP_CD
# ORDER BY 5월예약건수, 진료과코드

# SELECT MCDP_CD "진료과 코드", COUNT(APNT_NO) "5월예약건수" FROM APPOINTMENT
# WHERE APNT_YMD BETWEEN '2022-05-01' AND '2022-05-31'
# GROUP BY MCDP_CD
# 로 하면 ORDER BY할 때 "5월예약건수", "진료과 코드" 이런 식으로 하면 안 됨

SELECT MCDP_CD '진료과 코드', COUNT(APNT_NO) '5월예약건수' FROM APPOINTMENT
WHERE APNT_YMD < '2022-06-01'
AND APNT_YMD >= '2022-05-01'
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD