-- 아이스크림 성분 타입, 성분 타입에 대한 아이스크림의 총주문량
-- 총주문량이 작은 순서대로 조회
# SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
# FROM FIRST_HALF a JOIN ICECREAM_INFO b
# ON a.FLAVOR = b.FLAVOR
# GROUP BY INGREDIENT_TYPE
# ORDER BY TOTAL_ORDER

SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) TOTAL_ORDER
FROM FIRST_HALF f
JOIN ICECREAM_INFO i
ON f.FLAVOR = i.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC