-- 식품분류별로 가격이 제일 비싼 식품의 분류, 가격, 이름 조회
-- 식품분류가 '과자', '국', '김치', '식용유'인 경우만 출력
-- 식품 가격을 기준으로 내림차순 정렬

# WITH CTE AS
# (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
#  FROM FOOD_PRODUCT
#  WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#  GROUP BY CATEGORY)
# SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
# FROM FOOD_PRODUCT A JOIN CTE B
# ON A.CATEGORY = B.CATEGORY AND PRICE = B.MAX_PRICE
# ORDER BY PRICE DESC
    
# WITH CTE AS
# (SELECT ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) IDX, CATEGORY, PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자', '국', '김치', '식용유'))
# SELECT CATEGORY, PRICE, PRODUCT_NAME
# FROM CTE
# WHERE IDX = 1
# ORDER BY PRICE DESC

SELECT
    fp.CATEGORY,
    fp.PRICE AS MAX_PRICE,
    fp.PRODUCT_NAME
FROM FOOD_PRODUCT fp
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) m
  ON fp.CATEGORY = m.CATEGORY
 AND fp.PRICE = m.MAX_PRICE
ORDER BY fp.PRICE DESC;