# SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
# FROM BOOK a JOIN AUTHOR b
# ON a.AUTHOR_ID = b.AUTHOR_ID
# WHERE CATEGORY = '경제'
# ORDER BY PUBLISHED_DATE

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE FROM BOOK b
JOIN AUTHOR a
ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC